### ISSUE TITLE
How to set K and nGen for plant

### ISSUE THREAD

**Issue by dzaccook** [rwdavies/STITCH#36]
Hi,
I want to impute a plant in zingiberaceae using STITCH, and there are not any information about K and Ne, how can I determine (test) the K and nGen? I have 1500 samples and the genome size is ~3.2Gb, test different K may waste more time, is there some experience for set K and Ne?
Thank you!

**Comment by rwdavies** [comment]
I would recommend having a read through this
https://github.com/rwdavies/STITCH#note-on-the-selection-of-k-and-ngen
and let me know if you have additional questions? Simplly put, there's not an optimal way to do it, it requires a bit of trial and error for K. nGen should be more straightforward, the method is more robust to that parameter, and you use 4 * Ne / K for some estimate of the effective population size Ne if wild, and if non-wild, you can use some estimate of the number of generations since founding

**Comment by dzaccook** [comment]
Thank you!
