### ISSUE TITLE
error

### ISSUE THREAD

**Issue by smangul1** [rwdavies/STITCH#9]
Hi,

I have got this error when running : ./scripts/install-dependencies.sh

** R
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (rrbgen)
Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘rrbgen’

is it a problem?

Thanks,
Serghei

**Comment by smangul1** [comment]
Also another error

configure: error: liblzma not found, please install lzma (http://www.7-zip.org/sdk.html)
make: *** [SeqLib] Error 1
ERROR: compilation failed for package ‘STITCH’
* removing ‘/u/home/s/serghei/R/x86_64-pc-linux-gnu-library/3.4/STITCH’

**Comment by rwdavies** [comment]
Hm, the warning message is weird, but I just checked and it shows up in the build (https://travis-ci.org/rwdavies/STITCH/jobs/410058195#L2547) which is passing. If you open R is the library installed? (i.e. type "R" on command line then library("rrbgen") )

The lzma one is more annoying. This comes from the SeqLib dependency which I've seen before e.g. 
 https://github.com/walaj/bxtools/issues/19
and the related
https://github.com/samtools/htslib/issues/490
Are you able to ask an admin to install? Otherwise I've installed it myself without admin rights but it's annoying. I'll see if I can dig up the script and generalize it into stitch if lzma is not found

**Comment by rwdavies** [comment]
Hey, for the lzma / xz thing, I added a script and some instructions for how to install xz locally and make available to SeqLib. Can you try running the following and let me know if it works? 

```
./scripts/install-xz.sh
echo "CPPFLAGS += -I`pwd`/install/include" >> ~/.R/Makevars
echo "LDFLAGS += -I`pwd`/install/lib" >> ~/.R/Makevars
./scripts/build-and-install.sh
```

**Comment by rwdavies** [comment]
Sorry I forgot some stuff in the install-xz script. Let me check some things and get back to you

**Comment by rwdavies** [comment]
Sorry upon further inspection it did work properly on a system I have without xz or gmp etc installed. Let me know if it works for you

**Comment by rwdavies** [comment]
Closing this as suggestions above should fix this, and otherwise STITCH is in bioconda now and that should prevent this sort of problem
